#!/usr/bin/env bash

# Force root user.

if [[ "$(whoami)" != 'root' ]]; then
  echo 'Please run w/ `sudo`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap/src/bash/strict-mode;
. /bootstrap/src/bash/functions;

# Run setup scripts in this order now.

. /bootstrap-ci/src/docker/setups/ci-vars;
. /bootstrap-ci/src/docker/setups/env-vars;

# Run build scripts in this order now.

. /bootstrap-ci/src/docker/builds/phing;

# Run test scripts in this order now.

. /bootstrap-ci/src/docker/tests/mkdirs;
. /bootstrap-ci/src/docker/tests/wordpress;
. /bootstrap-ci/src/docker/tests/phing;
