#!/usr/bin/env bash

# Create directories.

mkdir --parents ~/ws/.persistent/apps &>/dev/null;
mkdir --parents ~/ws/.persistent/binaries &>/dev/null;
mkdir --parents ~/ws/.persistent/configs &>/dev/null;
mkdir --parents ~/ws/.persistent/repos &>/dev/null;

mkdir --parents ~/bin &>/dev/null;
mkdir --parents ~/ws/apps &>/dev/null;
mkdir --parents ~/ws/binaries &>/dev/null;
mkdir --parents ~/ws/cache &>/dev/null;
mkdir --parents ~/ws/configs &>/dev/null;
mkdir --parents ~/ws/logs &>/dev/null;
mkdir --parents ~/ws/logs/php &>/dev/null;
mkdir --parents ~/ws/logs/nginx &>/dev/null;
mkdir --parents ~/ws/tmp &>/dev/null;
mkdir --parents ~/ws/repos &>/dev/null;

mkdir --parents "${CI_CFG_LOGS_DIR}" &>/dev/null;
mkdir --parents "${CI_CFG_CACHE_DIR}" &>/dev/null;

if [[ -n "${CI_RUN_WP}" ]]; then
  mkdir --parents "${CI_CFG_WP_DIR}" &>/dev/null;
  ln --symbolic "${CI_CFG_WP_DIR}" ~/ws/www &>/dev/null;
else
  ln --symbolic "${CI_CFG_BUILD_DIR}" ~/ws/www &>/dev/null;
fi;
