#!/usr/bin/env bash

# Preamble with several build details.

echo; # First line is a spacer from other Travis details.
echo '--- CI Preamble ------------------------------------------------------';
echo;
echo 'Run vars: '"${CI_RUN}";
echo;
echo 'PHP Version: '"${CI_RUN_PHP_VERSION}";
echo 'PHP Version Name: '"${CI_RUN_PHP_VERSION_NAME}";
echo;
echo 'MySQL Version: '"${CI_RUN_MYSQL_VERSION}";
echo 'MySQL DB Host: '"${CI_CFG_MYSQL_DB_HOST}";
echo 'MySQL DB Port: '"${CI_CFG_MYSQL_DB_PORT}";
echo 'MySQL DB Charset: '"${CI_CFG_MYSQL_DB_CHARSET}";
echo 'MySQL DB Collate: '"${CI_CFG_MYSQL_DB_COLLATE}";
echo 'MySQL DB Username: '"${CI_CFG_MYSQL_DB_USERNAME}";
echo 'MySQL DB Password: '"${CI_CFG_MYSQL_DB_PASSWORD}";
echo 'MySQL DB Name: '"${CI_CFG_MYSQL_DB_NAME}";
echo;
echo 'Nginx Version: '"${CI_RUN_NGINX_VERSION}";
echo;
echo 'Build Host: '"${CI_CFG_BUILD_HOST}";
echo 'Build Port: '"${CI_CFG_BUILD_PORT}";
echo 'Build URL: '"${CI_CFG_BUILD_URL}";
echo 'Build Dir: '"${CI_CFG_BUILD_DIR}";
echo 'Build Dir Basename: '"${CI_CFG_BUILD_DIR_BASENAME}";

if [[ -n "${CI_RUN_WP}" ]]; then
  echo;
  echo 'WordPress Version: '"${CI_RUN_WP_VERSION}";
  echo 'WordPress Host: '"${CI_CFG_WP_HOST}";
  echo 'WordPress Port: '"${CI_CFG_WP_PORT}";
  echo 'WordPress URL: '"${CI_CFG_WP_URL}";
  echo 'WordPress Dir: '"${CI_CFG_WP_DIR}";
  echo 'WordPress DB Prefix: '"${CI_CFG_WP_DB_PREFIX}";
  echo 'WordPress Admin: '"${CI_CFG_WP_ADMIN}";
fi;
echo;
