#!/usr/bin/env bash

if [[ -f "${CI_CFG_PROJECT_DIR}"/build.xml ]]; then

  # Run tests via Phing.

  echo '--- Phing Test Process -----------------------------------------------';
  echo; # This starts the Phing test process.
  phing -f "${CI_CFG_PROJECT_DIR}"/build.xml test;
  echo; # If anything fails during the test, Phing exits.

  # Check for any PHP errors that occurred; e.g., during tests.

  if [[ -s /var/log/php/errors.log ]]; then
    echo '--- The following PHP errors were found in the log: ------------------';
    echo; # Display PHP error log for careful review.
    cat /var/log/php/errors.log; exit 1;
  fi;
  # Complete; i.e., indicate success w/ final output now.

  echo '--- Complete ---------------------------------------------------------';
  echo; # Indicate success in final output now.
  echo 'Testing success — fantastic!';

fi;
