#!/usr/bin/env bash

# Running as vagrant user?

if [[ "$(whoami)" != 'vagrant' ]]; then
  echo 'Please run w/ `vagrant`.'; exit 1; fi;

# Include strict mode & functions.

. /bootstrap-ci/src/bash/strict-mode;
. /bootstrap-ci/src/bash/functions;

# Run setup scripts in this order now.

. /bootstrap-ci/src/vagrant/setups/mkdirs;
. /bootstrap-ci/src/vagrant/setups/wordpress;

# Run build scripts in this order now.

. /bootstrap-ci/src/vagrant/builds/phing;
