Vagrant.configure(2) do |config|

  # Base image (box).
  config.vm.box = '%%box%%';

  # Configure memory allocation.
  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--memory', '2048'];
  end;
  # Mount `/bootstrap-ci` directory.
  config.vm.synced_folder '/bootstrap-ci', '/bootstrap-ci';

  # Mount `CI_CFG_PROJECT_DIR` directory.
  config.vm.synced_folder ENV['CI_CFG_PROJECT_DIR'], '/project-ci';

  # Run scripts as part of the provisioning process.
  config.vm.provision :shell, path: 'bootstrap-ci-vars';
  config.vm.provision :shell, path: 'bootstrap';

end;
