#!/usr/bin/env bash

# Update.

apt-get update;

# Install APT dependencies.

apt-get install ca-certificates --yes;
apt-get install apt-transport-https --yes;
apt-get install software-properties-common --yes;

# Add multiverse repo.

apt-add-repository multiverse --yes;
apt-get update; # Update again.
