#!/usr/bin/env bash

# Install Memcached daemon.

apt-get install memcached --yes;

# Config RAM allowance.

rm --force /etc/memcached.conf;
ln --symbolic /bootstrap/src/memcache/.conf /etc/memcached.conf;

# Restart service.

service memcached restart;
