#!/usr/bin/env bash

# Create directories.

mkdir --parents /etc/bootstrap;
mkdir --parents /var/bootstrap;
mkdir --parents /tmp/bootstrap;

mkdir --parents /var/log/bootstrap;
chmod 0777 /var/log/bootstrap;

mkdir --parents /tmp/bootstrap/cache;
chmod 0777 /tmp/bootstrap/cache;
