#!/usr/bin/env bash

# Install MariaDB (i.e., MySQL).

echo 'Package: *' >> /etc/apt/preferences.d/mariadb.pref;
echo 'Pin: release o=MariaDB' >> /etc/apt/preferences.d/mariadb.pref;
echo 'Pin-Priority: 1001' >> /etc/apt/preferences.d/mariadb.pref;

apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db;
add-apt-repository 'deb http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu trusty main';
apt-get update; # Update after adding new repo.

echo 'mariadb-server mysql-server/root_password password ciTNh5xXhsjNXwQ' | debconf-set-selections;
echo 'mariadb-server mysql-server/root_password_again password ciTNh5xXhsjNXwQ' | debconf-set-selections;
apt-get install mariadb-server --yes; # Install w/ the above options.

# Configure MySQL DB tables and permissions.

mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="GRANT ALL ON *.* TO 'client'@'localhost' IDENTIFIED BY 'ciTNh5xXhsjNXwQ';";
mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="GRANT ALL ON *.* TO 'client'@'127.0.0.1' IDENTIFIED BY 'ciTNh5xXhsjNXwQ';";
mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="GRANT ALL ON *.* TO 'client'@'%' IDENTIFIED BY 'ciTNh5xXhsjNXwQ' REQUIRE SSL;";

mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="CREATE DATABASE \`db0\` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';";

mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = '';";
mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="DELETE FROM \`mysql\`.\`user\` WHERE \`User\` = 'root' AND \`Host\` NOT IN ('localhost', '127.0.0.1', '::1');";
mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="DROP DATABASE IF EXISTS \`test\`; DELETE FROM \`mysql\`.\`db\` WHERE \`Db\` = 'test' OR \`Db\` LIKE 'test\\_%';";

mysql --user=root --password=ciTNh5xXhsjNXwQ --execute="FLUSH PRIVILEGES;";

# Config the MySQL/MariaDB server.

ln --symbolic /bootstrap/src/mysql/.cnf /etc/mysql/conf.d/z90.cnf;
echo '/bootstrap/src/mysql/.cnf r,' >> /etc/apparmor.d/local/usr.sbin.mysqld;

# Directories.

mkdir --parents /var/log/mysql;
chmod 0777 /var/log/mysql;

# Restart service.

service mysql restart;
