#!/usr/bin/env bash

# Install Ngnix web server.

apt-add-repository ppa:nginx/development --yes;
apt-get update; # Update after adding repo.
apt-get install nginx --yes;

# Config Ngnix web server.

rm --force /etc/nginx/nginx.conf;
rm --force /etc/nginx/sites-enabled/default;

mkdir --parents /etc/nginx/conf.d/http;
mkdir --parents /etc/nginx/conf.d/server;
ln --symbolic /bootstrap/src/nginx/.conf /etc/nginx/nginx.conf;

# Log directory.

mkdir --parents /var/log/nginx;
chmod 0777 /var/log/nginx;

# Setup default www directory.

chown --recursive www-data:www-data "${CI_CFG_BUILD_DIR}";
ln --symbolic "${CI_CFG_BUILD_DIR}" /var/bootstrap/www;

# Restart service.

service nginx restart;
