#!/usr/bin/env bash

# Install PHPUnit for tests.

if [[ "${CI_RUN_PHP_VERSION}" == 7.0 || "${CI_RUN_PHP_VERSION}" == 5.6 ]]; then
  _url=https://phar.phpunit.de/phpunit.phar;
else # Older version for older PHP installs.
  _url=https://phar.phpunit.de/phpunit-old.phar;
fi;
curl "${_url}" --location --output /usr/bin/phpunit;
chmod +x /usr/bin/phpunit; # Make it executable.
unset _url; # Housekeeping.
