#!/usr/bin/env bash

# Mount a RAM disk partition.

mkdir --parents /var/bootstrap/ram;
echo 'tmpfs /var/bootstrap/ram tmpfs defaults,size=12m,uid=nobody,gid=www-data,mode=2775 0 0' >> /etc/fstab;
mount /var/bootstrap/ram; # Mount the new partition.
