#!/usr/bin/env bash

# Install WP-CLI command-line utils.

curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar --location --output /usr/bin/wp;
chmod +x /usr/bin/wp; # Make it executable.

# Configure WP-CLI utilities.

echo 'user: admin' > /etc/bootstrap/wp-cli.yml;
echo 'path: /var/bootstrap/wp' >> /etc/bootstrap/wp-cli.yml;
echo 'url: https://ci.vm' >> /etc/bootstrap/wp-cli.yml;
echo 'allow-root: true' >> /etc/bootstrap/wp-cli.yml;

export WP_CLI_CONFIG_PATH; WP_CLI_CONFIG_PATH=/etc/bootstrap/wp-cli.yml;
