#!/usr/bin/env bash

# Adds a new global environment variable.

function add-global-env-var() {
  local key="${1:-}";
  local value="${2:-}";

  if [[ -z "${key}" ]]; then
    return 1; fi; # Must have.

  ## In real-time; export now.

  export "${key}"="${value}";

  ## System-wide; including CRON jobs.

  echo "${key}='${value}'" >> /etc/environment;

  ## Adds PHP-FPM environment variables.

  if [[ -d /etc/php/fpm ]]; then
    if [[ -f /etc/php/fpm/env.conf ]]; then
      if [[ "${value}" == '' ]]; then # FPM chokes on empty strings.
       # Single spaces are handled by /bootstrap/src/php/ap.php automatically.
        echo "env[${key}] = ' '" >> /etc/php/fpm/env.conf; # Use a single space.
      else echo "env[${key}] = '${value}'" >> /etc/php/fpm/env.conf; fi;
    else # Adds a file that our PHP-FPM installer can read from.
      if [[ "${value}" == '' ]]; then # FPM chokes on empty strings.
       # Single spaces are handled by /bootstrap/src/php/ap.php automatically.
        echo "env[${key}] = ' '" >> /etc/php/fpm/~env.conf; # Use a single space.
      else echo "env[${key}] = '${value}'" >> /etc/php/fpm/~env.conf; fi;
    fi;
  fi;
  ## Keep these environment variables when running `sudo`.
  ## Note that double quotes are required here.

  echo "Defaults env_keep += \"${key}\"" >> /etc/sudoers.d/env-vars;
};
