# Container.

dist: trusty
sudo: required
language: generic
script: ./.travis.bash

# Notifications.

notifications:
  email: false # Disable.
  webhooks: # Let WebSharks handle.
    urls: # This single URL will suffice.
      - https://www.websharks-inc.com/travis/webhook.php
    on_start: always
    on_success: always
    on_failure: always

# Build matrix rows (default configuration).

matrix: # Override this key for each project please.

  include: # Build configs to include.

    - env: CI_RUN=PHP_VERSION=7.0,WP=standard,WP_VERSION=latest
    - env: CI_RUN=PHP_VERSION=7.0,WP=multisite,WP_VERSION=latest
    - env: CI_RUN=PHP_VERSION=7.0,WP=standard,WP_VERSION=nightly
    - env: CI_RUN=PHP_VERSION=7.0,WP=multisite,WP_VERSION=nightly

  allow_failures: # Allow nightly failures.

    - env: CI_RUN=PHP_VERSION=7.0,WP=standard,WP_VERSION=nightly
    - env: CI_RUN=PHP_VERSION=7.0,WP=multisite,WP_VERSION=nightly

  fast_finish: true # Before allowed failures.

# Custom code reinserted here via [custom] marker. Add your <custom></custom> comment markers here please.
