#!/usr/bin/env bash

# Install PHP CLI and PHP process manager.

if [[ "${CI_RUN_PHP_VERSION}" == 7.0 ]]; then
  . /bootstrap/src/setups/php/via-ppa/v7.0;

elif [[ "${CI_RUN_PHP_VERSION}" == 5.6 ]]; then
  . /bootstrap/src/setups/php/via-ppa/v5.6;

elif [[ "${CI_RUN_PHP_VERSION}" == 5.5 ]]; then
  . /bootstrap/src/setups/php/via-ppa/v5.5;

elif [[ "${CI_RUN_PHP_VERSION}" == 5.4 ]]; then
  . /bootstrap/src/setups/php/via-ppa/v5.4;

else # Unexpected PHP version.
  echo 'Unexpected CI_RUN_PHP_VERSION environment variable.';
  exit 1; # Bail on failure.
fi;
